### ISSUE TITLE
quantity_input_args() determines doubled value if product is present in carts

### ISSUE THREAD

**Issue by pablopaul** [jamesgol/woocommerce-cart-stock-reducer#11]
## **Edited 05/08/2015 15:07**

Customer A has a pending cart with product X in it, Customer B also wants to add product X, then
`quantity_input_args()` determines a doubled "in carts quantity" for the max input arg since 

```
if ( true === $ignore && $result->option_name === '_wc_session_' . WC()->session->get_customer_id() ) {
  continue;
}
```

is never true for Customer B.

@jamesgol can you confirm this?

**Comment by jamesgol** [comment]
I'm on vacation till Sunday so I will have to look at this further when 
I get back but I don't believe this to be the case.  There is an 
argument to get_stock_available called $ignore which tells it to ignore 
items already in the cart.

**Comment by pablopaul** [comment]
Thanks for the quick reply

> There is an argument to get_stock_available called $ignore which tells it to ignore items already in the cart.

The `$ignore`argument is working but only for carts which belong to the actual user/woocommerce session:
`$result->option_name === '_wc_session_' . WC()->session->get_customer_id()`
Or do I get something wrong here?

**Comment by pablopaul** [comment]
@jamesgol Did you have any chance to look into it? Just a friendly reminder ;-) …

**Comment by jamesgol** [comment]
Sorry I haven't had a chance, summers are incredibly busy for me.  Next week I will start having more free time when the kids are in school.

**Comment by jamesgol** [comment]
Nice find, this is a fun one.  It's actually doubling up because when get_stock_available is called multiple times in the same session it keeps "tricking" Woo by decrementing the stock amount each time.  I'm going to add a flag to pass for that case but need to do some more testing to make sure it doesn't cause any other issues.

**Comment by jamesgol** [comment]
I just committed a fix that should take care of this.  I've tested it out and everything looks good in all of my tests, any chance you can test it out on your setup before I push the next version to the wordpress.org repo?

**Comment by pablopaul** [comment]
@jamesgol Thanks for your effort, I will test it during the next week.

18.09.2015: No testing progress so far for me, sorry.
