### ISSUE TITLE
Thanks for the shout-out at the changelog!

### ISSUE THREAD

**Issue by greguly** [jamesgol/woocommerce-cart-stock-reducer#13]
:-)

**Comment by greguly** [comment]
New filter  'woocommerce_get_stock_quantity' for WC2.5

 https://github.com/woothemes/woocommerce/pull/9149#issuecomment-141020215

**Comment by jamesgol** [comment]
Cool, thanks for letting me know.  I'll definitely change the code to take advantage of that, should make life a bit easier.

**Comment by greguly** [comment]
:-)
