### ISSUE TITLE
Not working with Woocommerce 2.5

### ISSUE THREAD

**Issue by juzzmoore** [jamesgol/woocommerce-cart-stock-reducer#16]
Seems that although warnings are displayed, the plugin does not successfully hold stock in Woocommerce 2.5.

**Comment by jamesgol** [comment]
Thanks for the report, I'll take a look today when I have a chance.

**Comment by juzzmoore** [comment]
Hi James,

Thanks so very much! Your plugin has been an incredibly valuable tool for my wife’s shop (www.minttheshop.com) as she sells one off retro items and her customers, listed at specific times.

Your time and effort is greatly appreciated!

Regards,
Justin Moore

**Comment by jamesgol** [comment]
Fix incoming, forgot that they moved session data to a new separate table (a good thing).

**Comment by juzzmoore** [comment]
Hi James,

Thanks so much! Again what a great plugin!

Cheers,

Justin
