### ISSUE TITLE
Suggested enhancements and documentation for global settings and FAQs

### ISSUE THREAD

**Issue by bluelotusworks** [jamesgol/woocommerce-cart-stock-reducer#2]
1. Minimum Stock to Skip Check - For the help tooltip, suggest including an example or two as the last sentence such as "For example, if you sell one of a kind items, the minimum stock to skip check should be set to 2. If carts are set to expire in an hour and you expect to sell 5 of an item during that period, the minimum stock to skip check should be set to 6."
2. Pending Order Text - Suggest adding some default text such as "Sorry, but there's a pending order for this item. It's not available for purchase."
3. Plugin FAQs - Suggest an FAQ regarding caching...
   What adjustments need to be made to caching?
   We recommend turning off page and database caching for pages affected by this plugin. For example, assuming your site uses the default Woocommerce "shop" page and W3 Total Cache, add "shop/*" (without the quotes) to "Never cache the following pages:" at the page cache and database cache settings.

**Comment by jamesgol** [comment]
Great notes, thanks!  I'll get them integrated tomorrow and hopefully cleanup the expiration stuff and push another release.

I need to do some testing with the different caching options and see what is really necessary.  Obviously caching is good most of the time but I suspect people with managed stock already have caching disabled on those pages.

**Comment by jamesgol** [comment]
Thanks! I got #2 and #3 added.  Have to think about #1, might be better to come up with more concise text and be more verbose in the readme

**Comment by jamesgol** [comment]
I added some text to the FAQ in the readme.txt and made a note that 'Minimum Stock to Check' is an advanced setting
