### ISSUE TITLE
Sidebar Cart / mini-cart update on automatic refresh

### ISSUE THREAD

**Issue by tomathyg** [jamesgol/woocommerce-cart-stock-reducer#20]
I have done some testing and discovered some issues when using the sidebar cart, both on the shop page and on a single product page.

(This is using a fresh installation of the latest version of Wordpress, on both the Twenty Sixteen and Twenty Fourteen themes, and with only Woocommerce and Cart Stock Reducer activated).

The cart is incorrectly updated in certain scenarios:

1) with a single simple product on the shop page

2) with two different simple products on the shop page

3) with two different simple products on one of the products' own pages

(With a single product on it's own page, everything works fine).

After the refresh, the following happens (respective of each scenario):

1) The page loops infinitely, re-adding the same product each time.

2) The first product is removed but the second product has 1 added to the quantity, this is then reduced back to 1 and then the item is removed on subsequent refreshes.

3) The first product is removed but the subtotal remains the same, then the second product is removed.

I've found that replacing the following lines in includes/class-woocommerce-cart-stock-reducer.php:

unset( $cart->cart_contents[ $cart_id ] ); (line 200)
WC()->session->set('cart', $cart->cart_contents); (line 201)

with:

$cart->remove_cart_item( $cart_id );

fixes scenario 3 and partially fixes scenario 1 (after the refresh the green message is still there but it doesn't loop).

However, it seems that more work is needed to completely fix this issue.

Tom

**Comment by jamesgol** [comment]
It seems you've discovered a fix that went into the github version but has not been released yet.  https://github.com/jamesgol/woocommerce-cart-stock-reducer/commit/1a8a628458e133ca3e0047d43e595e644be030a7

When I have a chance, I'll do some further testing to see what I uncover.

**Comment by tomathyg** [comment]
Ah, yes I see that now! I'm new to Github.

**Comment by tomathyg** [comment]
My scenario 3 is only fully fixed if line 201 is removed.

**Comment by jamesgol** [comment]
Can you give me some more specifics on the setup and how to reproduce them?  I tried various setups and could not reproduce the issue

**Comment by tomathyg** [comment]
Wordpress 4.4.2, Woocommerce 2.5.5, Twenty Fourteen. Single simple product on shop page just loops for me. Are you able to reproduce this?

**Comment by jamesgol** [comment]
No, I'm not able to reproduce this at all.  Can you give specifics on how the product is setup or any other differences? 

From the shop page when you click add to cart it sends off an AJAX request.  Maybe AJAX add to cart is disabled somehow?

**Comment by tomathyg** [comment]
Hi, sorry, yes AJAX is disabled. The timer doesn’t work at all with AJAX enabled.

**Comment by jamesgol** [comment]
With AJAX disabled I definitely see an issue, because the page refreshes based on the current URL.  I don't believe anyone has ever tested the plugin without AJAX enabled. 

What doesn't work with AJAX enabled?

**Comment by tomathyg** [comment]
That makes sense. Why not just have it follow the current url minus any query string?

At the moment, I don’t personally need AJAX disabled (I just tested every scenario to be thorough). My site currently only uses a single product page, which won’t use the Woocommerce AJAX function anyway.

I have a plugin to enable AJAX on this page (WooCommerce Ajax Add To Cart (oraksoft)) but it prevents the Cart Stock Reducer from working properly (the timer span is missing). I may try to fix this myself at some point. I’ll submit any changes I think would be useful.
