### ISSUE TITLE
Added to cart message and timer refer to different items when multiple items are added

### ISSUE THREAD

**Issue by tomathyg** [jamesgol/woocommerce-cart-stock-reducer#21]
When a second or third (fourth...) item is added to the cart, the first part of the message updates to reflect this but the timer only ever refers to the first item that was added - so the message is untrue.

Perhaps the initial added to cart timer should be reset each time an item is added, with a reminder that there are other items in the cart expiring sooner? Or a second timer for the earliest item in the cart? Or it could simply be reworded to make it clear that the timer is for the first item in the cart, not necessarily the latest.

**Comment by jamesgol** [comment]
Each item has it's own expiration timer.  If you want to adjust all timers there are actions and functions available that you can hook into to update all of the items expiration time.

If just adding an item to the cart resets the expiration time of everything then someone can keep items locked away just by continually adding more items to the cart.

**Comment by tomathyg** [comment]
Sorry, I perhaps didn't word that correctly.

I know that each item has it's own timer. I meant that the timer that is displayed with the 'item added to cart message', when a new item is added, should be the timer for the same item (not resetting any other timers).

Otherwise you have:

Item 1 added to cart. X minutes remaining before this item is removed.

Item 2 added to cart. X minutes remaining before this (actually item 1) is removed.

This is potentially confusing for the user as what the message is saying isn't true.

However, if it always displayed the latest timer, you would then have timers in the background refreshing the page when each previous item expires, which could be more confusing/poor UX.

I'm not sure what the best solution is, just raising the point really. A second timer showing the countdown for the next item to expire could be the answer, or a simple rewording of the message to say something like:

'Item 3 added to cart'. X minutes until this item expires. You have other items expiring sooner.

Ideally, each item in the cart would have a timer next to it and would be removed with Ajax.

I hope I'm explaining myself clearly enough!

Tom

**Comment by jamesgol** [comment]
I see what you are saying now, yes the text could be improved a bit.  I'll have to think a bit about this and see if one way makes more sense.  There are filters exposed so you can adjust this text yourself if you would like:

```
$this->item_expire_message = apply_filters( 'wc_csr_expire_notice', sprintf( __( 'Please checkout within %s or this item will be removed from your cart.', 'woocommerce-cart-stock-reducer' ), $item_expire_span ), $item_expire_span, $item[ 'csr_expire_time' ], $item[ 'csr_expire_time_text' ] );
```

I have individual timers in the cart on the TODO list.  I'll happily accept a pull request or funding to make this happen, otherwise it'll happen when time allows.

**Comment by tomathyg** [comment]
Ok, I think I’ll just amend the message for now. I may well submit a pull request in the near future (or if finances allow, I may offer some funding).

This plugin forms part of a booking system, which I need to be perfect! The built-in Woocommerce hold stock feature seems wildly inaccurate and of course there’s no visual cue for the customer to hurry up.

Anyway, thanks for your help.

Tom
