### ISSUE TITLE
Problem with adding products with variations (manage_stock: no) to a cart

### ISSUE THREAD

**Issue by levikmax** [jamesgol/woocommerce-cart-stock-reducer#22]
Hi. If we are adding products with variations (manage_stock: no) to a cart it writes 'Item is no longer available'.

**Comment by jamesgol** [comment]
Thanks for the report.  I see the issue and will release a fix after I test everything out

**Comment by jamesgol** [comment]
Issue is fixed in github.  I will push out a new version soon.  If you would like to try the latest version you can use https://github.com/jamesgol/woocommerce-cart-stock-reducer/archive/master.zip

**Comment by levikmax** [comment]
Thank you, it works! Waiting for the release.
