### ISSUE TITLE
Plugin language

### ISSUE THREAD

**Issue by FranciscoVillen** [jamesgol/woocommerce-cart-stock-reducer#26]
Hi,

I have translated the plugin front office to spanish (I have created .po and .mo files). I have modified the plugin to use the languages countdown js files so the words hours, minutes etc. are translated dependind on the language of the wordpress installation.

Maybe this could be useful for you, how could I send you these files?.

**Comment by jamesgol** [comment]
You can fork and submit a pull request here on github.  Please open a separate request for each major issue (translation file and plugin modification)
