### ISSUE TITLE
Timer not expiring if checkout page is left open.

### ISSUE THREAD

**Issue by nevernotrarekev** [jamesgol/woocommerce-cart-stock-reducer#28]
Hi there, to preface, we are using version 1.05 of your plugin using Woocommerce 2.4.12 and we've noticed that customers are still able to keep items in their cart during the checkout page for longer than our established expired time. In our case, 2 hours. 

A customer was able to purchase the same items in their cart 10 hours later. We are wondering if this plugin works on check out page? Do we need to update to the latest version? Thanks for your help in advance!

**Comment by jamesgol** [comment]
I would definitely upgrade and recheck, there have been several improvements made to attempt to keep that from happening.

**Comment by nevernotrarekev** [comment]
Thanks James!
