### ISSUE TITLE
IE Browser Caching Edge Case - Document Only

### ISSUE THREAD

**Issue by bluelotusworks** [jamesgol/woocommerce-cart-stock-reducer#3]
IE handles browser caching inconsistently vs FF and Chrome and we think the following is an edge case and wouldn't bother trying to fix it as we've seen it before without this plugin. 

After buying a variable item with quantity of one left in stock, if you go back to that variable product page without any browser refreshes, the variable just purchased is still listed as available. If you try to purchase it, you get an out of inventory error and then the variable is removed from the list. That doesn't happen with Firefox or Chrome...the variable just purchased is no longer listed the first time you go back to that variable product page.

**Comment by jamesgol** [comment]
That was exactly the reason I added the 'woocommerce_add_to_cart_validation' filter functions in.  We all know IE is silly, but if you are using FF/Chrome and you open one window on the item page and let it sit there and then go into another session and add that item to the cart you get the same results on the first window.

Hopefully when you did this in IE you saw the 'Item is no longer available' message.

**Comment by bluelotusworks** [comment]
With the scenario described above in IE, you do get the item is no longer available message (i.e., out of inventory error) when trying to add it to the cart. Not an ideal UX for IE users, but only have sympathy for those that have no choice but to use IE. Again, an edge case, just thought it a good idea to document it.
