### ISSUE TITLE
Not working on woocommerce 3.0.0

### ISSUE THREAD

**Issue by haruel** [jamesgol/woocommerce-cart-stock-reducer#39]
At least here is not working properly anymore, when i add some product that only has 1 in stock, i go to the cart to finish my buy and it says that is not possible because there is 0 item in stock... someone else is haaving the same issue ?

**Comment by tatusah** [comment]
James has been helpful with starting to fix this problem. It's not fully solved yet. But I'm going to test the sample code in the following thread, see this https://wordpress.org/support/topic/out-of-stock-notice/#post-9001575

**Comment by jamesgol** [comment]
I still need to do some more testing but if you would like to test the latest version, you can get it at https://github.com/jamesgol/woocommerce-cart-stock-reducer/archive/master.zip

I'm going to do a bit more work and release a new version very soon.

**Comment by jamesgol** [comment]
Plugin version 2.00 just released to wordpress.org.  Please test it out and let me know if you experience any issues

**Comment by xpafiolis** [comment]
Will install and test tonight. Thanks for your quick turn around! Any way to donate $$$?

**Comment by jamesgol** [comment]
There certainly is.  There is a donation button on: https://wordpress.org/plugins/woocommerce-cart-stock-reducer/

**Comment by xpafiolis** [comment]
Updated and seems to be working perfect with no errors on test site! Thanks again.

**Comment by trustedsec** [comment]
Not sure if this is related, but running into an issue where it'll show out of stock (quantity 0) but still show lets say 30 still in quantity - people can't purchase during that period, and doesn't update itself.. Using WooCommerce 3.0.5. Timer is working and all, but if the quantity is 30 - when people add to cart to start the counter, only one will go through - rest just show held and can't purchase. Max quantity is set to 4, so people can't purchase more than 4 at a time.

**Comment by jamesgol** [comment]
@trustedsec I can't say for certain if this is something that is fixed till I can try it out, but you should try the development version (https://github.com/jamesgol/woocommerce-cart-stock-reducer/archive/master.zip) and report back in a new ticket if it doesn't solve the issue.

**Comment by trustedsec** [comment]
Will do, thanks for the quick response. Appreciated.

**Comment by trustedsec** [comment]
Looks like grabbing the dev version fixed the issues and worked great. Thanks again.
