### ISSUE TITLE
Fatal error when Enable Stock Management at Product Level

### ISSUE THREAD

**Issue by tomwake** [jamesgol/woocommerce-cart-stock-reducer#41]
Hi,

We're using Wordpress 4.7.2 and WooCommerce 2.3.13.

When this plugin is enabled we're receiving a Fatal Error across the shop whenever the stock is checked, only if the option under Inventory to Manage Stock is selected.

We receive the following error - Fatal error: Call to undefined method WC_Product_Variable::get_id() in /wp-content/plugins/woocommerce-cart-stock-reducer/includes/class-woocommerce-cart-stock-reducer.php on line 652

It works for items where the Manage stock is not selected. Any help appreciated.

**Comment by tomwake** [comment]
Just looking at this further, does line 652 need to be -
`$id = $product->id;`
rather than
`$id = $product->get_id();`

**Comment by jamesgol** [comment]
It looks like WooCommerce added the get_id() function in 2.6.0, I only tested the code with the 2.6 and 3.0 major releases of WooCommerce.

2.3.13 is well over a year old, is there a particular reason you need to use it?

Changing from get_id() to id should probably work, but there might be other changes that would need to be made.  If you downgrade the plugin to the older 1.75 version it should work for you.

**Comment by tomwake** [comment]
Thanks for the reply. We'll try the other version and see if it works. 

We are planning an upgrade to 2.6 but due to complexities with the website it will take some time and we'd ideally like this plugin in place prior to then. Good work - it looks like really good and suitable for our needs.
