### ISSUE TITLE
prevent items from expiring when a user is on checkout page

### ISSUE THREAD

**Issue by apvlv** [jamesgol/woocommerce-cart-stock-reducer#44]
Hello and thank you for this wonderful plugin. 

During the testing of our page we found a frustrating issue. When a user is on the checkout page and an item in his cart expired at this time, in this moment he is unaware that he buys fewer products when he completes payment. Is it possible to prevent items from expiring when a user gets to checkout? or set a different expire time from this moment on?

Thank you!

**Comment by jamesgol** [comment]
There is a setting (named 'Ignore Order Status') to keep items from expiring if the order is in a certain state.  Most setups are going to be a bit different depending on which payment processor you use and how everything is setup, so there is no one size fits all.

**Comment by apvlv** [comment]
Thank you for your reply. Yes, thats true. But in my case i want to stop items from expiring before an actual order is made. So I don't have an order status, i want to stop expiring items when user enters checkout.

**Comment by apvlv** [comment]
Maybe I think in the wrong direction but how I would solve the problem, that the user adds an item to the cart, browses for a while maybe taking another item, goes to checkout and during checkout (he fills his credit card data in and his address) one of the items expire. Its an example when the expiration time is set to 15-30 min. I know, I can set the expiration time to 2 hours or so, but I want to tweak the process a bit more in detail. Thank you for your help!

**Comment by jamesgol** [comment]
I know there has been some previous discussion on this before but I don't think I ever implemented anything to handle it, but it should be possible with some existing WooCommerce hooks to deal with a situation like this.  

Though it does cause potential other problems, if someone wants to keep an item reserved they just keep refreshing the checkout page.

If you really want to do that, then the best bet would be to walk through each item expiring and add some time to the expiration countdown when the checkout page is loaded.  It might even be smart to make it so that only happens once so someone can't keep an item locked up by just refreshing the page.

**Comment by apvlv** [comment]
Thank you! So I probably would use the woocommerce_before_checkout_form hook? Do you have a small hint how I would walk through each item expiring for the particular users session?

**Comment by jamesgol** [comment]
Sorry for the delay.

It looks like I added a helper action a while back to deal with this issue.  So you can hook into that hook (or any of the others that happen around that point) and have it call the action 'wc_csr_adjust_cart_expiration'.
Example:
This will take all cart contents that expire and refresh the expiration, so if the original time was '5 minutes' this will add another 5 minutes to all items:
do_action( 'wc_csr_adjust_cart_expiration' );

You can also specify the amount of time to add:
do_action( 'wc_csr_adjust_cart_expiration', '1 hour' );

You can also extend specific cart item keys by passing them as the 3rd argument to the do_action() function call.

You can see the code that this calls here https://github.com/jamesgol/woocommerce-cart-stock-reducer/commit/1e3a3be9dd4a9da5b1857f28c6e7543bf6d3f8a3
and that also shows how to walk through each item in the cart :)

**Comment by apvlv** [comment]
Yes, thats exactly what I need! Thank you so much!

**Comment by jamesgol** [comment]
Old issue, but I just added some settings to auto refresh the cart in specific cases.
