### ISSUE TITLE
Fatal Error upon activation with Wordpress 4.8

### ISSUE THREAD

**Issue by MariemeMbengue** [jamesgol/woocommerce-cart-stock-reducer#45]
Hi there, 

I am running wordpress 4.8-en_CA. 
As soon as I activate the Woocommerce Cart Stock Reducer I get this error message: 

Fatal error: Uncaught Exception: Invalid order. in /home/jcfitzpa/public_html/oneofakind.world/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php:86 Stack trace: #0 /home/jcfitzpa/public_html/oneofakind.world/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(143): Abstract_WC_Order_Data_Store_CPT->read(Object(WC_Order)) #1 /home/jcfitzpa/public_html/oneofakind.world/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(109): WC_Data_Store->read(Object(WC_Order)) #2 /home/jcfitzpa/public_html/oneofakind.world/wp-content/plugins/woocommerce-cart-stock-reducer/includes/class-woocommerce-cart-stock-reducer.php(1137): WC_Abstract_Order->__construct(176) #3 /home/jcfitzpa/public_html/oneofakind.world/wp-content/plugins/woocommerce-cart-stock-reducer/includes/class-woocommerce-cart-stock-reducer.php(267): WC_Cart_Stock_Reducer->is_expired(1498167270, 176) #4 /home/jcfitzpa/public_html/oneofakind.world/wp-content/plugins/woocommerce-cart-stock-reducer/includes/ in /home/jcfitzpa/public_html/oneofakind.world/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php on line 86

I have no idea how to resolve the issue. 
Thank you for your help!

**Comment by jamesgol** [comment]
Based on the trace I suspect you have some existing carts/uncompleted transactions in WooCommerce.  You can clear all the sessions through the WooCommerce interface and that should take care of it.

If possible, I would love to get a dump of your database before you do that so I can reproduce the issue and make sure it doesn't happen in the future.

**Comment by MariemeMbengue** [comment]
Hi James,

Thank you for the quick reply. 
Please walk me through the steps to get you the database info you need. I am not familiar with the process.

**Comment by jamesgol** [comment]
Do you have phpmyadmin or some other way to export a backup of the database?

**Comment by MariemeMbengue** [comment]
I can export the database from phpmyadmin. I have a choice between a quick (display only the minimal options) or custom method (display all possible options) and I also have a choice of format to export to.
What do you need?

**Comment by jamesgol** [comment]
If you select custom and keep all the defaults but set the compression to gzip or zip (either is fine) the file will be smaller.  This will contain all of your passwords and almost everything else on your site, so if you don't want to share this I would understand.   You could also select specific tables,
 wp_woocommerce_sessions is probably the most important one but reproducing the setup would be easier with all the data.

If you have a site with a lot of content this could also be rather large file.  You can email this to me at james@gnuinter.net, definitely don't post it publicly

**Comment by MariemeMbengue** [comment]
I am just starting on the website so there is not a whole lot of content. 
Thanks for the heads up about passwords. If you could tell me which tables contain passwords and sensitive information I could exclude those and email you the rest of the data.

**Comment by jamesgol** [comment]
The wp_users table would have the passwords in it.  wp_options also can contain some sensitive info but it also could contain some WooCommerce configuration data that would be useful.

**Comment by MariemeMbengue** [comment]
It's working perfectly after clearing the session.
Thank you very much for helping me so quickly.
Cheers!

**Comment by jamesgol** [comment]
Happy to hear it.  I'll close this out, but investigate the issue so nobody else runs into it in the future.
