### ISSUE TITLE
An issue with stock message

### ISSUE THREAD

**Issue by daron4ever** [jamesgol/woocommerce-cart-stock-reducer#47]
I have a variable product with stock status.
Normally, for example, "10 in stock" displayed.
But I have "in stock" message with your plugin. The number of stock volume is missing.

**Comment by jamesgol** [comment]
Is this stock managed by the individual product or the main product?  Can you tell me what version of the plugin and WooCommerce you are using?

**Comment by daron4ever** [comment]
It is variable products so the stock is managed by the individual product with this plugin Version 2.10 / WooCommerce Version 3.1.2

**Comment by jamesgol** [comment]
In my recent testing I've been unable to reproduce this issue, but a while back I did make a change in the development version which might have been related.  I'm going to be pushing a new release out in the next day or two, you could test the dev version here or wait to test the release.
