### ISSUE TITLE
Need admin option to force clear user carts and/or update inventory levels

### ISSUE THREAD

**Issue by Garconis** [jamesgol/woocommerce-cart-stock-reducer#49]
I have a product with 302 variations. Each variation only has 1 quantity available. However, somehow some of the inventory levels for these variations are stuck as being held. 

It may be a result of me testing before I originally set a time limit. So perhaps these items are still stuck in someone's cart somewhere? I need to be able to bulk set the qty levels for each variation back to 1. I've done that through the normal WooCommerce product variation area. All variations show a stock of 1. However, the ones that are missing/pending are being shown as "Out of Stock". So I set this back to "In Stock". But upon saving the product, it sets it back to "Out of Stock". 

So somewhere, it's stuck as "pending". The stock issue is fixed when I uncheck "Enable Cart Stock Reducer".

I need a way to "reset" stock back to what is shown in the WooCommerce variation area.

**Comment by jamesgol** [comment]
Wow, that's a lot of variations.  I'm sure the issue is that there are items in someones cart but haven't expired yet (or expiration is not enabled).  If you use the WooCommerce clear sessions button it will wipe out all the active carts/sessions and the issue should go away.

**Comment by Garconis** [comment]
Yes, I just saw this issue: https://github.com/jamesgol/woocommerce-cart-stock-reducer/issues/23

That seemed to fix it after I cleared that data, and after I reset all the variations to be "In Stock" again. Thanks! Hopefully going forward, these will properly become "In Stock" again after the interval I specified. :)
