### ISSUE TITLE
Pending Order Text Issues with Simple and Variable Products

### ISSUE THREAD

**Issue by bluelotusworks** [jamesgol/woocommerce-cart-stock-reducer#5]
Four UX items to address related to the pending order text message. May be edge cases for some web sites, but part of "normal" customer behavior on others.
1. At a simple product page that has inventory of more than one, if you add one at a time to the cart, the pending order text message appears when taking the last one in inventory although it is added to the cart. The purchase of all items can be completed. The same thing happens at a variable product page for variations that have inventory of more than one. FYI, if you input a quantity that takes all items in inventory for a simple or variable product, WC behaves properly and the pending order text message does not appear.
2. At a variable product page that has inventory of one for each variable, when adding a second, third, fourth, etc variable to a cart, it's added but the pending order text message is received upon each cart addition. The purchase of all items can be completed.
3. At a variable product page that has inventory of more than one for each variable, after adding any quantity of the first variable, if all of another variable is taken, it's added but the pending order text message is received upon each cart addition. The purchase of all items can be completed.
4. After a cart expires, when going back to add a variable item, the pending order text message is received starting with the first item. The purchase of all items can be completed.

**Comment by jamesgol** [comment]
The pending order text should always be displayed if there are 0 items available for purchase.  So I'd say the buggy cases are the ones where it doesn't.  I guess the text needs to be cleared up so the user knows that their items are in stock but no more can be added.  I'm not sure what would make the most sense to an end user
- If user already has that item in their cart set the text to 'Insufficient quantity to purchase more items'
- Count the number of items in the cart for the user and append something that tells them "Not including your X items"
- Something else?

I'm getting some occasional browser caching when I use the back button.  I'll see if I can kill that.

**Comment by bluelotusworks** [comment]
Regarding 1 above, my comment "FYI, if you input a quantity that takes all items in inventory for a simple or variable product, WC behaves properly and the pending order text message does not appear." That's incorrect, the pending order text message does appear (maybe I was moving too fast in testing last night).

However, what's noted for 1 and 3 and what's in the first paragraph of this comment is the expected  result, correct? In that case, when taking the last item in inventory, I think the second alternative you suggest is preferable. In relation to that, I suggest changing the default pending order text message to "This item is no longer available for purchase at this time due to pending orders." with an append of "Pending orders include X items added to your cart".

**Comment by jamesgol** [comment]
That's correct, that is the expected result.  I've changed the default text to 'This item is not available at this time due to pending orders.'  

I've added the appending to the todo list which already has: Add option of displaying when an item might be available in addition to the 'stock_pending' message.

**Comment by bluelotusworks** [comment]
After thinking about it, the proposed change resolves item 4 too. For consistency, regarding item 2, perhaps the pending order text message should appear when selecting the first product as well as the 2nd, 3rd, 4th, etc?

**Comment by jamesgol** [comment]
Just added some code to take care of all this.  Going to wait a bit for some more testing and then release a new version to wordpress.org in a few days

**Comment by ahmadsyukri** [comment]
Hai,
I got same error with this too...
http://prnt.sc/c9cr0r 
"This item is not available at this time due to pending orders." 
Any solution for this?

**Comment by jamesgol** [comment]
@ahmadsyukri please open a new issue with your specific information.  Generally most issues for new users are resolved by clearing existing cart information in WooCommerce.
