### ISSUE TITLE
Broken after upgrade to WP 4.8.3

### ISSUE THREAD

**Issue by hyvellasse** [jamesgol/woocommerce-cart-stock-reducer#53]
After upgrading to WP 4.8.3, all products get the status that they are in a cart and are not available.
If I disable Cart Stock Reducer in woocommerce the problem disappear. Ok I know that is not tested for 4.8.3 but Cart Stock Reducer is a very good feature. Especially when you have products that exists only in one copy.

Best regards

**Comment by jamesgol** [comment]
Thanks for the report, I haven't had a chance to test with the released 4.8.3 but I know I did some testing while it was in development.  I'll have to track that down when I get a chance.

**Comment by jamesgol** [comment]
I just tested with WordPress 4.8.3 and the latest WooCommerce and don't see any problems.  I tested with this plugin dev version and 2.10.  Are you using different versions?

**Comment by hyvellasse** [comment]
I also have Woocommerce 3.2.2 and Cart Stock Reducer 2.10.

**Comment by jamesgol** [comment]
Which message are you getting?  I tried reproducing with some other settings and haven't been able to get it to fail

**Comment by hyvellasse** [comment]
When I open a product I get the messages that I have configured in the Woocommerce configuration/Integration "Pending Order Text" And I get this on all products.

**Comment by jamesgol** [comment]
Odd that I can't reproduce this.  Can you try clearing the WooCommerce sessions/carts?

**Comment by hyvellasse** [comment]
Ok how do I do that. :-)

**Comment by jamesgol** [comment]
WooCommerce (menu)->Status (submenu)->Tools (Tab)->Clear customer sessions (button)

**Comment by hyvellasse** [comment]
Ok I think this helped I can't see the problem any more after i have turned on the Cart Stock Reducer.
I also tested to add a product to the basket and remove it. And all seems to be working.
I get the  "Pending Order Text" when adding. And the "Pending Order Text" disappear when removing the product from the basket.

Thanks for the help.

**Comment by jamesgol** [comment]
Glad it's working.  If you run into any more issues please open up another ticket.
