### ISSUE TITLE
 Decimal Stock Quantity

### ISSUE THREAD

**Issue by wikiexir** [jamesgol/woocommerce-cart-stock-reducer#57]
Hi
I’m using “woocommerce cart stock reducer” plugin in my site. this works wery well with its amazing abilities But there is a problem that i cant fix it. (remind that my products are virtual)
I use another plugin called “Quantities and Units for WooCommerce” that allows Stock Quantity and Quantity field to be decimal. (for example users can buy 0.2 unit of a product)
when a product quantity goes less than 1 (for example 0.25) the “woocommere cart stock reducer” plugin makes it 0 and Prints the “out of stock” massage in the product page althogh my users can buy 0.1 unit of a product!
when i deactivate the “woocommerce cart stock reducer” my users can buy products with amounts less than 1 !!!
how can i fix this problem that allow my users to buy some amount of a product that have less than 1 unit in stock.
thanks for your help

**Comment by jamesgol** [comment]
Fixed in latest development version
