### ISSUE TITLE
Add time to expiration on checkout page

### ISSUE THREAD

**Issue by jamesgol** [jamesgol/woocommerce-cart-stock-reducer#6]
It occurred to me it might be useful to have a configurable amount of time added to expiration if the user hits the checkout page.  It would have to be a one time addition to keep people from refreshing checkout page to keep extending the time and locking an item out.

Any thoughts/opinions?

**Comment by bluelotusworks** [comment]
Nice to have, but...

While I've been testing at 10 minutes, I'll probably set cart expiration to 15-20 minutes longer term which should give someone plenty of time to complete checkout without that option.

**Comment by jamesgol** [comment]
With the new action 'wc_csr_adjust_cart_expiration' action this can be adjusted if someone really wanted to do this.
