### ISSUE TITLE
not work with WPML

### ISSUE THREAD

**Issue by omried** [jamesgol/woocommerce-cart-stock-reducer#61]
i try to use this plugin but its not worked with WPML.
i have a product with 50 pcs in stock.
when i use A language i add 25 pcs to the cart
i open B language in my phone and add 30 pcs and its let me to add it to the cart.
anyone have a sulotion?

**Comment by jamesgol** [comment]
Duplicate of #60 

It is on the TODO list, but I have not had sufficient available free time yet to work on it.

**Comment by hzengler** [comment]
Hi James, 

Thank you for your amazing free plugin. I am about to install it on a website and I wanted to know if you found the time to get it work with WPML or if it's still on your TODO list ? :)

Thank you
