### ISSUE TITLE
Item is immediately removed after being added to cart

### ISSUE THREAD

**Issue by 4n0n1mo** [jamesgol/woocommerce-cart-stock-reducer#62]
I get the message that it was added to the cart and immediately get this message:
"Sorry, 'Porduct' was removed from your cart because you didn't checkout before the expiration time."

The expiration time is set to 30 (should be 30 minutes right?). I don't get why it's immediately removing it.

I have the latest WP and WC versions.
Using Sober theme.

**Comment by jamesgol** [comment]
What exactly is the expiration time set to?  
The settings page gives examples what to use (Examples: 10 minutes, 1 hour, 6 hours, 1 day)

If you are passing just '30' then the PHP strtotime (https://secure.php.net/manual/en/function.strtotime.php) function won't return anything useful

**Comment by 4n0n1mo** [comment]
Sorry, my mistake.
This plugin is just awesome! It solves one of the biggest bugs on Woocommerce.
