### ISSUE TITLE
Got a product variation stuck

### ISSUE THREAD

**Issue by 4n0n1mo** [jamesgol/woocommerce-cart-stock-reducer#63]
I've installed the plugin, enabled the expiration time, have set to '30' only. Obviously it was a wrong value.

Now that I've inserted the value '30 seconds' it works fine but the product that was reduced when the value was only '30' is stuck at the pending order text, is like it wasn't removed, and as I have used a guest account (chrome private browsing) to put it on the cart and closed the page, it's stuck at the guest session.

It doesn't seems to be a caching problem, because it works fine on other products.

Please check it, click on 'P' size.
It's pending, and the expiration time is set to 30 seconds, it should have been gone already :(

Also, thank you very much for developing this.

**Comment by jamesgol** [comment]
Your best bet is to clear the WooCommerce sessions to empty the carts/sessions through the WooCommerce settings menu

**Comment by 4n0n1mo** [comment]
Ok, will try, thanks! Keep up the good work.
