### ISSUE TITLE
Expiration Time to Pending Order Text not displaying

### ISSUE THREAD

**Issue by bonste** [jamesgol/woocommerce-cart-stock-reducer#67]
Hi James,

thanks for your plugin, it's great!

I am having one issue with the 'Append Expiration Time to Pending Order Text', it is currently not showing up, while both the 'Pending Order Text' and the 'Append Included Items to Pending Order Text' do show up.

Do you know if anyone else is having the same issue?

Thanks,
Stefi
<img width="586" alt="screen shot 2018-07-01 at 7 13 10 pm" src="https://user-images.githubusercontent.com/40732893/42132828-da09e346-7d62-11e8-8871-11729deb2604.png">

<img width="972" alt="screen shot 2018-07-01 at 7 14 58 pm" src="https://user-images.githubusercontent.com/40732893/42132853-1db7501a-7d63-11e8-97d9-dd83bc510bbe.png">

**Comment by jamesgol** [comment]
I am currently out of town but my first guess at this without seeing the
configuration is that pending text probably won't show when it's the
current session that has the item in your cart.  Does it get displayed if
you check the product page from an anonymous session or other browser?

**Comment by bonste** [comment]
Thank you for replying even though you are away James.
I have checked and it happens even from an anonymous session or other browser.

Also, although it has been more than 1 hour, the product still appears as 'out of stock'.

Thank you again,
Stefi

**Comment by jamesgol** [comment]
If the product is not expiring out of the cart and the configuration is right then I wonder if the product was added to the cart before the plugin was activated.  In that case there would be no expiration time set in the cart item entry.  Clearing all cart sessions through WooCommerce would be a good step to do (assuming it won't affect any valid orders)

Can you take a screenshot of the plugin configuration page and anything unique about the product configuration?

**Comment by jamesgol** [comment]
Any luck?

**Comment by bonste** [comment]
Sorry, I haven't had a chance to look at it yet. I'll look tonight and let
you know.

Thank you!!

**Comment by bonste** [comment]
Hi James,

it is working now. You were correct, I must have had that object in the
cart before enabling the plugin.

Thank you for your help!
Stefi
