### ISSUE TITLE
Header - Products Table

### ISSUE THREAD

**Issue by rakelcita** [jamesgol/woocommerce-cart-stock-reducer#73]
Hi!
I have a problem, in my list of products, the header is not OK, and the column where have to appear the quantity in carts is wrong. I paste here 2 screenshot.

Thank you!

![captura](https://user-images.githubusercontent.com/45955245/50126781-9cb0c780-026e-11e9-87a3-ef7bc1633a1d.JPG)
![captura2](https://user-images.githubusercontent.com/45955245/50126908-29f41c00-026f-11e9-86d0-165303f2122e.JPG)

**Comment by jamesgol** [comment]
Wow, that looks bad, I'll have to check on the css for the header.

What is the quantity in carts expected to be?  It's difficult to troubleshoot without some additional information

**Comment by jamesgol** [comment]
If you want to test the development version on here the styling issue should be resolved there.

**Comment by rakelcita** [comment]
> Wow, that looks bad, I'll have to check on the css for the header.
> 
> What is the quantity in carts expected to be? It's difficult to troubleshoot without some additional information

Sorry for my English I wanted to say that I can not see the quantity in carts because these numbers are over price number. There isn't  space between columns.

**Comment by rakelcita** [comment]
> If you want to test the development version on here the styling issue should be resolved there.

Yes! I'd like to test the development version... What have I to do?

**Comment by jamesgol** [comment]
You can checkout the version with git from github or download the zip file https://github.com/jamesgol/woocommerce-cart-stock-reducer/archive/master.zip

**Comment by rakelcita** [comment]
I've just tested and now everything is ok!
Thank you very much :)

**Comment by jamesgol** [comment]
Excellent, thanks for testing.  I'm not sure when I will release the next version but the update will certainly be in there.
