### ISSUE TITLE
Fatal error PHP - some times

### ISSUE THREAD

**Issue by knutsp** [jamesgol/woocommerce-cart-stock-reducer#79]
`PHP Fatal error:  Uncaught Error: Call to a member function managing_stock() on bool in /home/*/public_html/wp-content/plugins/woocommerce-cart-stock-reducer/includes/class-woocommerce-cart-stock-reducer.php:710`
Stack trace:
```
#0 /home/*/public_html/wp-content/plugins/woocommerce-cart-stock-reducer/includes/class-woocommerce-cart-stock-reducer.php(587): WC_Cart_Stock_Reducer->get_item_managing_stock(false, 102758, NULL)
#1 /home/*/public_html/wp-includes/class-wp-hook.php(288): WC_Cart_Stock_Reducer->add_cart_validation(true, 102758, 1)
#2 /home/*/public_html/wp-includes/plugin.php(206): WP_Hook->apply_filters(true, Array)
#3 /home/*/public_html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(407): apply_filters('woocommerce_add...', true, 102758, 1)
#4 /home/*/public_html/wp-includes/class-wp-hook.php(288): WC_AJAX::add_to_cart('')
#5 /home/*/public_html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
#6 /home/*/public_html/wp-includes/plugi in /home/*/public_html/wp-content/plugins/woocommerce-cart-stock-reducer/includes/class-woocommerce-cart-stock-reducer.php on line 710
```

**Comment by jamesgol** [comment]
Can you provide some information?  

What version of WooCommerce are you using?  What other WooCommerce related plugins were you using?  Type of product?

It's clear the problem happened when adding to cart via ajax but can you provide any more context?

**Comment by knutsp** [comment]
Thanks for answering so quick!

PHP 7.4.3
WP 5.3.2
WooCommerce 3.9.3
Autocomplete WooCommerce Orders 1.1.0
Mailchimp for WooCommerce 2.3.3
Bambora Online Checkout

My own, site specific plugin, but does not interfere with carts or stock, no manipulation of WC_Product or WC_Order objects during processing. Just admin UI, custom taxonomy and extra checkout fields and order meta fields. No ajax, no scripts.

Both options are enabled (stock reducing and cart timeout),

Special: Pendig/future products are purchasable when they have a regular price (by filter).

Theme: Elementor Pro

All products are single, virtual (no variants or externals). No shippping (fields/taxes). For booking courses.

I have only the error_log. No order was successfully created at exact that time, and happened at about 10 am, but not busy.  No other errors or warnings at same time. Happened once so far, today, few times last weeks.

This could be an artefact, but since it fatals, one can't know. Just happy if you look into it, may be add some checking/protection so processing can continue, in case meaningful in this case. I haven't studied the code, as my understanding of cart handling is a bit weak.

Now upgrading WooCommerce. Will report back if it happens again.

**Comment by knutsp** [comment]
Happened again
`Uncaught Error: Call to a member function get_id() on bool in /wp-content/plugins/woocommerce-cart-stock-reducer/includes/class-wc-csr-sessions.php:56
Stack trace:

#0 /wp-includes/class-wp-hook.php(303): WC_CSR_Sessions->woocommerce_prevent_adjust_line_item_product_stock()
#1 /wp-includes/plugin.php(189): WP_Hook->apply_filters()
#2 /wp-content/plugins/woocommerce/includes/admin/wc-admin-functions.php(208): apply_filters()
#3 /wp-content/plugins/woocommerce/includes/admin/wc-admin-functions.php(351): wc_maybe_adjust_line_item_product_stock()
#4 /wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-items.php(54): wc_save_order_items()
#5 /wp-includes/class-wp-hook.php(305): WC_Meta_Box_Order_Items::save()
#6 /wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#7 /wp-includes/plugin.php(470): WP_Hook->do_action()
#8 /wp-content/plugins/woocommerce/includes/admin/class-wc-admin-meta-boxes.php(222): do_action()
#9 /wp-includes/class-wp-hook.php(305): WC_Admin_Meta_Boxes->save_meta_boxes()
#10 /wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#11 /wp-includes/plugin.php(470): WP_Hook->do_action()
#12 /wp-includes/post.php(4468): do_action()
#13 /wp-includes/post.php(4570): wp_insert_post()
#14 /wp-admin/includes/post.php(423): wp_update_post()
#15 /wp-admin/post.php(227): edit_post()
#16 {main}`

**Comment by jamesgol** [comment]
~~What version of the plugin was this with?~~ Nevermind, I can see that it's a recent version because the WC_CSR_Sessions->woocommerce_prevent_adjust_line_item_product_stock() function didn't exist till recently.

This is different than the last one.  You were saving a product change and this happened?

**Comment by knutsp** [comment]
WCSR 3.75

Saving an edited order.

**Comment by knutsp** [comment]
As last time, bool treated as object. A returned object that doesn't exist (false)?

**Comment by jamesgol** [comment]
What type of products were in the order you were editing?  Something is very strange here.  I know you said you had all simple products before but this is weird because that call checks to see if the $item has a callable 'get_product' function.

If you try to redo the same action does the same result happen?

**Comment by jamesgol** [comment]
I did a quick look through the plugins you said you were using before and the free elementor theme and didn't see anything that hooks a filter to any of the WooCommerce filters that should affect this.  Do you have any other plugins active?

You mentioned 'Special: Pendig/future products are purchasable when they have a regular price (by filter).'  is this some custom code you have?  Can you share it?

**Comment by knutsp** [comment]
There are 52 plugins, but only a few about WooCommerce. There was no pending/future products at this time. The custom code is quite huge, but nothing related to either product stock (that's why using plugin), "`get_product()`" method nor calling `'woocommerce_order_item_product'` filter.

I can't redo. Not me operating the shop.

You call `get_product()`, usually returning a `WC_Product` object, but **may return false** as  documented here https://woocommerce.github.io/code-reference/classes/WC-Order-Item-Product.html#method_get_product

I can look through  the custom code if you can give me a hint.

**Comment by jamesgol** [comment]
I'd just look for any WooCommerce related filter that is supposed to return a product but is returning false.  While those docs say it may return boolean I've never found an instance where it actually does so when given proper inputs (obviously if you call get_product() on something that is not a product it will do so)

I'm happy to add additional checks but that's more of a band aid to cover up some other hidden problem that might show it's head in other ways.

**Comment by knutsp** [comment]
I made an interview with operator, and the case is that a product was deleted (before removing from all processing orders). Then a new item with the another (new) product was added manually. Since this was done in the opposite sequence as recommended (by me), this problem is suddenly less serious (known cause/trigger).

BUT: The documentation is correct and real. If the product is no longer in a published state (or even permanently deleted) "get_product()" will return false.

**Comment by jamesgol** [comment]
Always good to know a cause.  I'll have to do some further testing on deleted or unpublished products.

**Comment by jamesgol** [comment]
I can confirm that when permanently deleting an item from WooCommerce and then trying to delete the item from a cart would cause the traceback.  The fix I committed earlier does resolve that issue.

Let me know if you uncover other issues like this, whenever I find time to add proper automated testing that will have to be one of the edge cases to test.

**Comment by knutsp** [comment]
Sure.

We are now on PHP 8.0 and some errors are more serious than PHP 7.4. No need to downgrade PHP now, as this is explained and will look forward to a fix. Such may happen again, here and there.

Btw: This plugin have saved client and me from big trouble with overbooking (the products are curses/classes with fixed "stock"). The site has **very** loyal customers (participants), and for a two hour period, only eight times a year, just after release of new course schedule, the traffic is huge. Temporary reducing stock while in cart was the solution, with flexible timing. Thanks for making it!

**Comment by jamesgol** [comment]
I haven't had a chance to test this out with PHP 8.0, if you run into any issues with it please let me know.
