### ISSUE TITLE
How to move a move an function from a hook to another

### ISSUE THREAD

**Issue by christiaen-francois** [jamesgol/woocommerce-cart-stock-reducer#85]
Hi, my theme is not very compatible with some hooks. I would like to move some notifications from **woocommerce_before_single_product** to **woocommerce_single_product_summary** but I don't know how... 

Can you tel us how to do this ?

**Comment by jamesgol** [comment]
Duplicate from WordPress forums https://wordpress.org/support/topic/how-to-remove_action/
