### ISSUE TITLE
No expiry for some products

### ISSUE THREAD

**Issue by taenzer** [jamesgol/woocommerce-cart-stock-reducer#90]
hey,

i wonder if its possible to set the expirition time for some products to infinite... iam selling tickets and merchandise. tickets should expire, merch not. how could i realize that? maybe with the 'csr_expire_time' field?

Thanks for your help!

**Comment by jamesgol** [comment]
Sometime soon there will probably be a checkbox to enable expiration per item, but for now you could use the 'csr_expire_time' field.  Set the default expiration time to whatever you have the most products of (tickets or merchandise) and then set the post meta 'csr_expire_time' on the other to that value.  Use 'never' as the time for the merchandise so it doesn't ever expire.

**Comment by taenzer** [comment]
Thank you really much for your fast reply! Works great.
