### ISSUE TITLE
WooCommerce - Minimum/Maximum Quantities plugin

### ISSUE THREAD

**Issue by PowderValley** [jamesgol/woocommerce-cart-stock-reducer#91]
When a customer adds item to cart with a Maximum set on the item there is a warning that says exceeds maximum. When you add the maximum to the cart and go to cart you can't add any more in the cart as well.

Now with Cart stock reducer enabled the warning doesn't pop up, it just doesn't allow you to add it to your cart. When you do get under the maximum it allows you to add to your cart. Which is fine but the catch is when you get into your cart you can add as many as you want while in your cart.

Min/Max Plugin: http://www.wpeliteplugins.com/downloads/woocommerce-minimum-maximum-quantities/

**Comment by jamesgol** [comment]
If you send me a copy of the Min/Max plugin I'll do some testing when I find some time to work on this plugin.

**Comment by PowderValley** [comment]
Here is the plugin. I can also get you access to our staging website for testing as well if you want to email me direct. jacob.love@powdervalleyinc.com
[WooCommerce MinMax Quantities Plugin.zip](https://github.com/jamesgol/woocommerce-cart-stock-reducer/files/6631714/WooCommerce.MinMax.Quantities.Plugin.zip)

**Comment by jamesgol** [comment]
I took a quick glance at the code (don't have time for proper testing right now).  It looks like in several cases they override the maximum quantity allowed regardless of any other plugin.

Can you provide some info on your setup.
What is the min/max allowed configured with that plugin?
Are backorders allowed?
What is the quantity for the specific item?
What type of item (simple, variation, etc.)?

**Comment by PowderValley** [comment]
Can you provide some info on your setup.
`
### WordPress Environment ###

WordPress address (URL): https://www.powdervalleyinc.com
Site address (URL): https://www.powdervalleyinc.com
WC Version: 5.3.0
REST API Version: ✔ 5.3.0
WC Blocks Version: ✔ 4.9.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.2.6
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.18.0
PHP Version: 7.4.14
PHP Post Max Size: 512 MB
PHP Time Limit: 600
PHP Max Input Vars: 6000
cURL Version: 7.29.0
NSS/3.53.1

SUHOSIN Installed: –
MySQL Version: 5.7.12
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.0.0
WC Database Prefix: wp_
Total Database Size: 10657.25MB
Database Data Size: 5930.01MB
Database Index Size: 4727.24MB
wp_woocommerce_sessions: Data: 16.45MB + Index: 0.39MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 45.58MB + Index: 16.55MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 316.86MB + Index: 327.83MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 1.47MB + Index: 0.59MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 133.17MB + Index: 86.31MB + Engine InnoDB
wp_actionscheduler_claims: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 66.61MB + Index: 49.13MB + Engine InnoDB
wp_cmeb_email_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmeb_free_domains: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_cmeb_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmeb_userlist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 7.52MB + Index: 9.03MB + Engine InnoDB
wp_comments: Data: 144.69MB + Index: 99.31MB + Engine InnoDB
wp_gpi_api_error_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gpi_custom_urls: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gpi_page_blacklist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gpi_page_reports: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gpi_page_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gpi_summary_snapshots: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_grp_google_place: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_grp_google_review: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 247.47MB + Index: 3.06MB + Engine InnoDB
wp_pmxe_exports: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_posts: Data: 9.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_templates: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 10.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.45MB + Index: 0.00MB + Engine InnoDB
wp_podsrel: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 1828.00MB + Index: 920.00MB + Engine InnoDB
wp_posts: Data: 59.59MB + Index: 32.14MB + Engine InnoDB
wp_redirection_404: Data: 1407.03MB + Index: 366.77MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.31MB + Index: 0.38MB + Engine InnoDB
wp_redirection_logs: Data: 2.02MB + Index: 3.05MB + Engine InnoDB
wp_taxjar_record_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_termmeta: Data: 0.17MB + Index: 0.23MB + Engine InnoDB
wp_terms: Data: 0.38MB + Index: 0.41MB + Engine InnoDB
wp_term_relationships: Data: 2.52MB + Index: 2.52MB + Engine InnoDB
wp_term_taxonomy: Data: 0.48MB + Index: 0.48MB + Engine InnoDB
wp_usermeta: Data: 314.89MB + Index: 365.91MB + Engine InnoDB
wp_users: Data: 21.55MB + Index: 23.58MB + Engine InnoDB
wp_wcextraflatrate_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcextraflatrate_shipping_zone_locations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcextraflatrate_user_zone: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 7.52MB + Index: 7.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 20.55MB + Index: 24.06MB + Engine InnoDB
wp_wc_order_stats: Data: 10.52MB + Index: 10.55MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.23MB + Index: 0.20MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 1.52MB + Index: 1.08MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 4.30MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 45.63MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 1.52MB + Index: 0.28MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 14.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 1.02MB + Index: 0.23MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 2.02MB + Index: 0.69MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wps_hit: Data: 713.00MB + Index: 2086.14MB + Engine InnoDB
wp_wps_index: Data: 36.56MB + Index: 46.22MB + Engine InnoDB
wp_wps_key: Data: 1.19MB + Index: 1.27MB + Engine InnoDB
wp_wps_object_term: Data: 7.14MB + Index: 12.36MB + Engine InnoDB
wp_wps_object_type: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wps_query: Data: 18.55MB + Index: 20.56MB + Engine InnoDB
wp_wps_uri: Data: 318.88MB + Index: 160.98MB + Engine InnoDB
wp_wps_user_agent: Data: 7.52MB + Index: 3.52MB + Engine InnoDB
wp_wt_iew_action_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 52.58MB + Index: 37.44MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.36MB + Index: 0.47MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_prominent_words: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_yoast_seo_links: Data: 5.50MB + Index: 3.80MB + Engine InnoDB
wp_yoast_seo_meta: Data: 10.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

_pods_field: 3
_pods_pod: 2
attachment: 6740
custom_css: 2
customize_changeset: 1
jetpack_migration: 2
manufacture_rebate: 8
nav_menu_item: 84
oembed_cache: 48
page: 39
post: 46
product: 3898
product_variation: 1666
revision: 866
seedprod: 1
shop_coupon: 15
shop_order: 218429
shop_order_refund: 235
wc_afrsm: 12
wc_conditional_fee: 8
wcp_ruleset: 1
woo_discount: 11
woo_discount_cart: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (46) ###

Query Monitor: by John Blackbourn – 3.7.1
Pods - Custom Content Types and Fields: by Pods Framework Team – 2.7.28
a3 Lazy Load: by a3rev Software – 2.4.5
AddToAny Share Buttons: by AddToAny – 1.7.44
Admin CSS MU: by Arun Basil Lal – 2.6
Advanced Flat Rate Shipping For WooCommerce (Premium): by theDotstore – 3.7.2
Akismet Anti-Spam: by Automattic – 4.1.9
Block User Account: by Mahmoud Zooroofchi – 1.3.0
Contact Form 7 Google Analytics Intelligence: by LevelTen – 1.1.2
Cloudflare: by Cloudflare
Inc. – 4.5.1

CM E-Mail Registration Blacklist Pro: by CreativeMindsSolutions – 1.5.7
Conditional Payments for WooCommerce: by Lauri Karisola / WooElements.com – 2.2.3
Contact Form 7: by Takayuki Miyoshi – 5.4.1
Delta WooCommerce Notice: by Delta Systems Group – 1.0.0
Drip for WooCommerce: by Drip – 1.1.2
IgniteWoo Updater: by IgniteWoo.com – 3.0.2
Kirki Customizer Framework: by David Vongries – 3.1.6
Pods - Custom Content Types and Fields: by Pods Framework Team – 2.7.28
Pods - Custom Content Types and Fields: by Pods Framework Team – 2.7.28
reCaptcha for WooCommerce: by I Thirteen Web Solution – 2.16
Redirection: by John Godley – 5.1.1
Search By SKU - for Woocommerce: by Unroll Digital – 0.7.1
SendGrid: by SendGrid – 1.11.8
Vantiv WooCommerce Gateway: by Radial Studios – 2.1.0
WooCommerce Cash On Pickup: by Marian Kadanka – 1.6
Woo Discount Rules: by Flycart – 2.3.7
WooCommerce - Minimum/Maximum Quantities: by WPElitePlugins – 2.0.5
Wholesale For WooCommerce Lite: by wpexpertsio – 1.5.4
WooCommerce Cart Stock Reducer: by James Golovich – 3.40
WooCommerce Conditional Product Fees for Checkout Pro: by Multidots – 1.2.7
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.8.11 (update to version 1.9.5 is available)
Print Invoice & Delivery Notes for WooCommerce: by Tyche Softwares – 4.6.2
WooCommerce Extra Product Sorting Options: by SkyVerge – 2.9.0
WooCommerce Authorize.Net Gateway: by SkyVerge – 3.6.0
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.1
WooCommerce Google Analytics Integration: by WooCommerce – 1.5.1
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.9.0
WooCommerce Product Dependencies: by SomewhereWarm – 1.2.6
WooCommerce Product Search: by itthinx – 3.7.0
Woocommerce Products Per Page: by Jeroen Sormani – 1.2.6
WooCommerce Shipment Tracking: by WooCommerce – 1.6.26
WooCommerce: by Automattic – 5.3.0 (update to version 5.4.1 is available)
Wordfence Security: by Wordfence – 7.5.4
Yoast SEO Premium: by Team Yoast – 16.4
Yoast SEO: by Team Yoast – 16.4
Yoast SEO: WooCommerce: by Team Yoast – 13.7

### Inactive Plugins (8) ###

CIO Custom Fields Importer Pro: by <a href="http://vipp.com.au">VisualData</a> – 1.3.1
WooCommerce Checkout Add-Ons: by SkyVerge – 2.5.4
WP All Export Pro: by Soflyy – 1.6.3
WP All Import - WooCommerce Add-On Pro: by Soflyy – 3.2.5
WP All Import Pro: by Soflyy – 4.6.5
WP Sheet Editor - WooCommerce Orders Pro: by WP Sheet Editor – 1.2.12
WP Sheet Editor - WooCommerce Products (Premium): by WP Sheet Editor – 1.7.2
Yoast Test Helper: by Team Yoast – 1.14

### Dropin Plugins (3) ###

db-error.php: db-error.php
db.php: Query Monitor Database Class
maintenance.php: maintenance.php

### Must Use Plugins (3) ###

tripointhosting-loadbalancer-cookie: by Byron DeLaMatre –
tripointhosting-security: by Byron DeLaMatre –
tripointhosting-ssl-verify: by Byron DeLaMatre –

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
simple (simple-2)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: #119723 - /terms-and-conditions/

### Theme ###

Name: Powder Valley 2018
Version: 999.999.999 (Tyche v1.0.11)
Author URL: https://deltasys.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: tyche/woocommerce/archive-product.php version 2.0.0 is out of date. The core version is 3.4.0
tyche/woocommerce/checkout/terms.php version 3.1.1 is out of date. The core version is 3.4.0
tyche/woocommerce/checkout/thankyou.php version 3.2.0 is out of date. The core version is 3.7.0
tyche/woocommerce/content-single-product.php version 3.0.0 is out of date. The core version is 3.6.0
tyche/woocommerce/emails/customer-on-hold-order.php version 2.5.0 is out of date. The core version is 3.7.0
tyche/woocommerce/emails/plain/customer-on-hold-order.php version 2.5.0 is out of date. The core version is 3.7.0
tyche/woocommerce/global/sidebar.php
tyche/woocommerce/loop/add-to-cart.php version 3.0.0 is out of date. The core version is 3.3.0
tyche/woocommerce/single-product/add-to-cart/external.php version 2.1.0 is out of date. The core version is 3.4.0
tyche/woocommerce/single-product/add-to-cart/grouped.php version 3.0.7 is out of date. The core version is 4.8.0
tyche/woocommerce/single-product/add-to-cart/simple.php version 3.0.0 is out of date. The core version is 3.4.0
tyche/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php version 3.0.0 is out of date. The core version is 3.4.0
tyche/woocommerce/single-product/tabs/tabs.php version 2.4.0 is out of date. The core version is 3.8.0
tyche/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update

### Authorize.Net Credit Card ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off
Webhooks Enabled: ✔

### Action Scheduler ###

Canceled: 1
Oldest: 2021-05-10 13:12:55 -0500
Newest: 2021-05-10 13:12:55 -0500

Complete: 256,896
Oldest: 2021-05-10 11:15:25 -0500
Newest: 2021-06-10 12:04:13 -0500

Failed: 446
Oldest: 2019-12-20 07:44:49 -0600
Newest: 2021-06-05 10:47:17 -0500


### Status report information ###

Generated at: 2021-06-10 12:04:29 -05:00

What is the min/max allowed configured with that plugin?
Not sure I understand this question

Are backorders allowed?
No they are not.

What is the quantity for the specific item?
Maximum of 1 
Inventory: 35

What type of item (simple, variation, etc.)?
Variation is what we noticed on.

**Comment by jamesgol** [comment]
> What is the min/max allowed configured with that plugin?
> Not sure I understand this question

This Min/Max plugin, presumably you are setting a minimum and maximum quantity that are allowed to be purchased.  Though maybe your followup that says 'Maximum of 1' is the answer I'm looking for.

If you are using this plugin to allow people to only buy one of something, why aren't you just using the builtin WooCommerce functionality for this?

**Comment by PowderValley** [comment]
That was just one example. Some of the items is 2, 5 or 10. We change it according to supply and demand.

**Comment by jamesgol** [comment]
> That was just one example. Some of the items is 2, 5 or 10. We change it according to supply and demand.

That's why I asked, need all the information.  WooCommerce has many edge cases where things are handled just slightly different.


> What type of item (simple, variation, etc.)?
> Variation is what we noticed on.

Is it only happening on variation or you just only noticed it there?  

Is the problem only on the cart page?  So the product page allows the correct count but on the cart page you are able to adjust the quantity?  What is the limit you are able to go above?  The currently available quantity (from Cart Stock Reducer) or the maximum quantity (from Min/Max plugin)?

**Comment by PowderValley** [comment]
How it normally functions (Simple Item, Limit 25)
![image](https://user-images.githubusercontent.com/85643085/121585039-be323a80-c9f7-11eb-93b4-1a555636f73a.png)
![image](https://user-images.githubusercontent.com/85643085/121585099-d0ac7400-c9f7-11eb-913f-14e0f07861c9.png)

This is what happens once the cart stock reducer is enabled:

Clicked add to cart, page just reloaded. No warning trying to add 30.
![image](https://user-images.githubusercontent.com/85643085/121585470-3f89cd00-c9f8-11eb-8a81-1d7b7fd03ae3.png)

Reduce down to 25
![image](https://user-images.githubusercontent.com/85643085/121585536-52040680-c9f8-11eb-8cf0-54f09a548ca9.png)

Now that the 25 are in the cart click "view cart" change quantity to 30 hit update cart and it accepts it.
![image](https://user-images.githubusercontent.com/85643085/121585669-76f87980-c9f8-11eb-847d-92c3dc8f2351.png)

We see these same things happen on Simple and Variable items.

**Comment by jamesgol** [comment]
Thank you for the images, you know what they say a picture is worth a...  

Though can you clarify which plugins are active for each picture? You say the first two are "normal" and then the following with cart stock reducer enabled, but in all except the 3rd image I see cart stock reducer type messages.

**Comment by PowderValley** [comment]
First two picture settings
![image](https://user-images.githubusercontent.com/85643085/121588329-67c6fb00-c9fb-11eb-9441-900790b424bf.png)

Last three picture settings
![image](https://user-images.githubusercontent.com/85643085/121588395-7ad9cb00-c9fb-11eb-833d-673d7130128e.png)

**Comment by jamesgol** [comment]
I just commited a change that should resolve this issue.  Any way you can test out the development version?

**Comment by PowderValley** [comment]
I tested and it is now fixed on the Product page but not on the cart screen.

**Comment by jamesgol** [comment]
That's odd, it is as expected for me.  My test I set a simple product to 'max quantity' of 5 with 25 in stock and it will only let me adjust up to 5.

**Comment by PowderValley** [comment]
Let me clear our cache.

**Comment by PowderValley** [comment]
> That's odd, it is as expected for me. My test I set a simple product to 'max quantity' of 5 with 25 in stock and it will only let me adjust up to 5.

That is on the product page or the Cart page?

I cleared cache and now it quit working on the product page.

Here is a link to the product on our page. You can test with it.

https://www.powdervalleyinc.com/product/hornady-172-17-20-gr-vmax-100/

**Comment by jamesgol** [comment]
On my test it is working properly on the product page and the cart page.

On that page you linked it appears the max is set to 127?

**Comment by PowderValley** [comment]
Max is set to 25
![image](https://user-images.githubusercontent.com/85643085/121597650-95657180-ca06-11eb-8cd0-b278df85d3b8.png)

**Comment by PowderValley** [comment]
Inventory is 132

**Comment by jamesgol** [comment]
I setup a product with those exact numbers and the latest development version and it is working as expected on the product and cart page. 

From the product page or cart page if you inspect the quantity box it shows the max value allowed.  In this case it's 132:

`<input type="number" id="quantity_60c281461d4f2" class="input-text qty text" step="1" min="1" max="132" name="quantity" value="1" title="Qty" size="4" placeholder="" inputmode="numeric" data-cip-id="quantity_60c281461d4f2">
`

It should be showing 25.  Are you sure you have the development version on your live site?

**Comment by PowderValley** [comment]
Where is the development version of the plugin?

**Comment by jamesgol** [comment]
Here on github.  You can checkout the branch or download a zip of the latest https://github.com/jamesgol/woocommerce-cart-stock-reducer/archive/refs/heads/master.zip

**Comment by PowderValley** [comment]
It worked!! Appreciate it!!

**Comment by jamesgol** [comment]
Excellent.  This fix will be in an upcoming released version.
