### ISSUE TITLE
Doesn't work properly when kinsta caching

### ISSUE THREAD

**Issue by jameshwartlopez** [jamesgol/woocommerce-cart-stock-reducer#92]
Notification that the item has been reserved is not showing.

**Comment by jamesgol** [comment]
I don't know anything about kinsta.  Can you set your pages not to cache?  Many caching plugins respect the nocache constants the plugin sets, but there might be some code changes necessary for their setup.  If you can find out details about a constant or header that needs to be set to not cache it should be easy to solve.

**Comment by jamesgol** [comment]
Need additional info, reopen if you are still having an issue and want to provide more info
